version: "3.9"
services:
  haproxy:
    ports:
      - "80:80"
    image: pbayona/haproxy
    depends_on:
      - web1
      - web2
      - serviciointerno
      - serviciointerno2
  web1:
    ports: 
     - "9090:8443"
     - "5702:5701"
    volumes:
     - .:/todo
    image: pbayona/web1
    depends_on:
     - db
     - serviciointerno
     - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/sapio?createDatabaseIfNotExist=true
      - SERVICE_SOCKETIP=haproxy
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATASOURCE_PASSWORD=SapiothecaF4
      - WEB_HOSTS=web1,web2
  web2:
    ports: 
     - "9091:8443"
     - "5701:5701"
    volumes:
     - .:/todo
    image: pbayona/web1
    depends_on:
     - db
     - serviciointerno
     - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/sapio?createDatabaseIfNotExist=true
      - SERVICE_SOCKETIP=haproxy
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATASOURCE_PASSWORD=SapiothecaF4
      - WEB_HOSTS=web1,web2
  db:
    image: mysql:8.0.23
    environment:
      - MYSQL_ROOT_PASSWORD=SapiothecaF4
      - MYSQL_DATABASE=sapio
      - MYSQL_PASSWORD=SapiothecaF4
      
  rabbitmq:
    image: rabbitmq    
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
    - "15672:15672"
    - "5672:5672"
    
  serviciointerno:
    ports:
    - "8080:8080"
    - "9999:9999"
    volumes:
    - .:/todo
    image: pbayona/serviciointerno
    depends_on:
      - db
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/sapio?createDatabaseIfNotExist=true
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATASOURCE_PASSWORD=SapiothecaF4

  serviciointerno2:
    ports:
    - "8081:8080"
    - "10000:9999"
    volumes:
    - .:/todo
    image: pbayona/serviciointerno
    depends_on:
      - db
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/sapio?createDatabaseIfNotExist=true
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATASOURCE_PASSWORD=SapiothecaF4
  