version: "3.9"
services:
  web1:
    build: .
    ports: 
     - "9090:8443"
    volumes:
     - .:/todo
    image: pbayona/web1
    depends_on:
     - db
     - serviciointerno
     - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/sapio?createDatabaseIfNotExist=true
      - SERVICE_SOCKETIP=serviciointerno
      - SPRING_RABBITMQ_HOST=rabbitmq
     
  db:
    image: mysql:8.0.23
    environment:
      - MYSQL_ROOT_PASSWORD=SapiothecaF4
      - MYSQL_DATABASE=sapio
      - MYSQL_PASSWORD=SapiothecaF4
      
  
  rabbitmq:
    image: rabbitmq    
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
    - "15672:15672"
    - "5672:5672"
    
  serviciointerno:
    build: .
    ports:
    - "8080:8080"
    - "9999:9999"
    volumes:
    - .:/todo
    image: pbayona/serviciointerno
    depends_on:
      - db
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/sapio?createDatabaseIfNotExist=true
      - SPRING_RABBITMQ_HOST=rabbitmq
  