version: "3.9"
services:
  web1:
    build: .
    ports: 
     - "9090:8443"
    volumes:
     - .:/todo
    links:
     - db
     - serviciointerno
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/sapio?createDatabaseIfNotExist=true
     
  db:
    image: mysql:8.0.23
    environment:
      - MYSQL_ROOT_PASSWORD=SapiothecaF4
      - MYSQL_DATABASE=sapio
      - MYSQL_PASSWORD=SapiothecaF4
  
  rabbitmq:
    image: rabbitmq
    
  serviciointerno:
    build: .
    ports:
    - "8080:8080"
    volumes:
    - .:/todo
    image: sergioe17/serviciointerno
    links:
      - db
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/sapio?createDatabaseIfNotExist=true
  