version: "3.9"
services:
  web1:
    build: .
    ports: 
     - "9090:8443"
    volumes:
     - .:/todo
    links:
     - db
     - serviciointerno
  db:
    image: mysql:8.0.23
  
  rabbitmq:
    image: rabbitmq
    
  serviciointerno:
    build: .
    ports:
    - "8080:8080"
    volumes:
    - .:/todo
    image: sergioe17/serviciointerno
    links:
      - db
      - rabbitmq
  